/**
 * Vercel entry point. The production build creates dist/server.cjs before
 * Vercel packages this function. Loading it dynamically avoids extensionless
 * ESM resolution failures in the Vercel Node runtime.
 */
export default async function handler(req: any, res: any) {
  try {
    // The bundle is generated by `npm run build` and included by vercel.json.
    // @ts-expect-error The generated CommonJS bundle is not type-declared.
    const serverModule = await import('../dist/server.cjs');
    const appPromise = serverModule.default ?? serverModule;
    const app = await appPromise;
    return app(req, res);
  } catch (error) {
    console.error('[Vercel API] Express startup failed:', error);
    return res.status(503).json({ success: false, error: 'API_STARTUP_FAILED' });
  }
}
